apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: security-enforcement-agent
  namespace: edge-agents
spec:
  selector:
    matchLabels:
      app: security-agent
  template:
    metadata:
      labels:
        app: security-agent
    spec:
      hostNetwork: true
      hostPID: true
      terminationGracePeriodSeconds: 30
      nodeSelector:
        edge.kubeedge.io/exclude-cni: "true"
      initContainers:
      - name: veth-setup
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            ip link add veth-br-sec type veth peer name veth-sec || true
            ip link set veth-br-sec up
            ip link set veth-sec up
            ovs-vsctl add-port br0 veth-br-sec || true
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-mount
          mountPath: /dev
        - name: ovsdb-socket
          mountPath: /var/run/openvswitch
      containers:
      - name: enforcement-agent
        image: henok28/security-enforcement-agent:v2
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: KAFKA_BROKER
          value: "192.168.56.121:31896"
        - name: ONOS_URL
          value: "http://192.168.56.121:8181"
        - name: OVS_BRIDGE
          value: "br0"
        - name: ENFORCE_MODE
          value: "onos"
        ports:
        - name: prom-metrics
          containerPort: 9000
        - name: flow-api
          containerPort: 5005
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        # livenessProbe:
        #   httpGet:
        #     path: /api/flows
        #     port: 5005
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /api/flows
        #     port: 5005
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        volumeMounts:
        - name: dev-mount
          mountPath: /dev
        - name: ovsdb-socket
          mountPath: /var/run/openvswitch
      volumes:
      - name: dev-mount
        hostPath:
          path: /dev
      - name: ovsdb-socket
        hostPath:
          path: /var/run/openvswitch
