apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telemetry-collector
  namespace: edge-agents
spec:
  selector:
    matchLabels:
      app: telem-collector
  template:
    metadata:
      labels:
        app: telem-collector
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 30
      nodeSelector:
        edge.kubeedge.io/exclude-cni: "true"
      tolerations:
        - key: "node-role.kubeedge.io/edge"
          operator: "Exists"
          effect: "NoSchedule"
      restartPolicy: Always

      initContainers:
      - name: veth-setup
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            ip link add veth-br-telemetry type veth peer name veth-telemetry || true
            ip link set veth-br-telemetry up
            ip link set veth-telemetry up
            ovs-vsctl add-port br0 veth-br-telemetry || true
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-mount
          mountPath: /dev
        - name: ovsdb-socket
          mountPath: /var/run/openvswitch

      containers:
      - name: collector
        image: henok28/telemetry-collector:v4
        imagePullPolicy: Always
        securityContext:
          privileged: true

        env:
        - name: MQTT_BROKER_HOST
          value: "127.0.0.1"
        - name: MQTT_BROKER_PORT
          value: "1883"
        - name: MQTT_TOPIC
          value: "devices/#"
        - name: KAFKA_BOOTSTRAP
          value: "192.168.56.121:31896"
        - name: KAFKA_SECURITY_PROTOCOL
          value: "PLAINTEXT"
        - name: TOPIC_RAW
          value: "telemetry-raw"
        - name: TOPIC_ALERTS
          value: "telemetry-alerts"

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

        volumeMounts:
        - name: dev-mount
          mountPath: /dev
        - name: ovsdb-socket
          mountPath: /var/run/openvswitch

      volumes:
      - name: dev-mount
        hostPath:
          path: /dev
      - name: ovsdb-socket
        hostPath:
          path: /var/run/openvswitch
