apiVersion: v1
kind: Service
metadata:
  name: cloudcore
  namespace: kubeedge
spec:
  type: NodePort
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  ports:
  - name: websocket
    port: 10000
    targetPort: 10000
    nodePort: 30000
  - name: quic
    port: 10001
    protocol: UDP
    targetPort: 10001
    nodePort: 30001
  - name: https
    port: 10002
    targetPort: 10002
    nodePort: 30002
  - name: stream
    port: 10003
    targetPort: 10003
    nodePort: 30003
  - name: tunnel
    port: 10004
    targetPort: 10004
    nodePort: 30004
