apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.8.0
    replicas: 3

    listeners:
      # 1) Internal overlay listener
      - name: plain           # DNS: kafka-cluster-kafka-bootstrap.kafka:9092
        port: 9092
        type: internal
        tls: false

      # 2) External NodePort listener
      - name: external
        port: 9094
        type: nodeport        # Exposes Kafka on nodePort 9094 for external access
        tls: false

    # (Optional) tune topic / transaction replication
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2

    # Ephemeral storage for easy rebuilds; switch to pvc if you need persistence
    storage:
      type: ephemeral

  zookeeper:
    replicas: 3
    storage:
      type: ephemeral

  entityOperator:
    topicOperator: {}
    userOperator: {}
